---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

Today we're making interactive plots in plotly. We'll make examples using the NYC airbnb dataset.

```{r message = FALSE}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

Do some initial data cleaning / subsetting.

```{r}
data("nyc_airbnb")

nyc_airbnb =
  nyc_airbnb |>
  mutate(rating = review_scores_location / 2) |>
  select(rating, neighbourhood_group, neighbourhood,
         room_type, lat, long, price) |>
  drop_na(rating) |>
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
  )

```

Use plotly to make some quick plots.

Scatterplot
```{r}
nyc_airbnb |> 
  mutate(text_label = 
           str_c("Price: ", price, 
                 "\nNeighbourhood: ", neighbourhood)) |>
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

Box plot 
```{r}
nyc_airbnb |>
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |>
  plot_ly(x = ~neighbourhood, y = ~price, color = ~neighbourhood,
          type = "box", colors = "viridis")
```

Bar chart 
```{r}
nyc_airbnb |>
  count(neighbourhood) |>
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |>
  plot_ly(x = ~neighbourhood, y = ~n,
          type = "bar")
```

